version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      # KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  
  neo4j:
    image: neo4j:4.2.3
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/some_password

  producer_app:
    build:
      context: .
      dockerfile: Dockerfile-producer
    depends_on:
      - kafka
    

  consumer_app:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    depends_on:
      - kafka
      - elasticsearch
      - neo4j
